version: '3.8'

services:
  nginx:
    depends_on:
      - calendar-ui
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "80:80"

  calendar-ui:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
